In [ ]:
import sys
sys.version

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from numpy import linalg as LA

import warnings
warnings.filterwarnings('ignore')

%matplotlib inline

# Solving Linear Equation

In [2]:
A = np.array([[4, -5], [-2, 3]])
b = np.array([[-13], [9]])

x = LA.inv(A).dot(b)

print (x)

[[ 3.]
 [ 5.]]


# Vector - vector Product

In [9]:
x = np.array([[1], [1]])
y = np.array([[2], [3]])

x.transpose().dot(y)

array([[5]])

# Diagonal

In [11]:
d = np.array([1, 2, 3])
D = np.diag(d)

print (D)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


# Norm

In [13]:
x = np.array([[4], [3]])

LA.norm(x,2)

5.0

In [15]:
LA.norm(x,1)

7